ignore:
  - "src/main/java/com/Components/*Component*.java"  # ignore folders and all its contents
  - "src/main/java/com/Client/*View*.java"
  - "src/main/java/com/Components/*.java"
  - "*.java"       # wildcards accepted
  - "**/*.java"         # glob accepted
  - "[a-z]+/_.*"  # regexp accepted
  - "**/*View*/**/*"
  - "**/*Dashboard*"
  - "**/*ComboBox*"
  - "**/*Component*"

codecov:
  notify:`
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
